"""abstract

Revision ID: 1cab54a1a0ce
Revises: 58712c0e9ecb
Create Date: 2024-10-11 17:40:27.168016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cab54a1a0ce'
down_revision = '58712c0e9ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
