"""abstract

Revision ID: 58712c0e9ecb
Revises: 622278450afb
Create Date: 2024-10-11 17:37:47.120872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58712c0e9ecb'
down_revision = '622278450afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
