"""abstract

Revision ID: c4aee1a5c72d
Revises: 1cab54a1a0ce
Create Date: 2024-10-12 15:30:38.052219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4aee1a5c72d'
down_revision = '1cab54a1a0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
